package GUI;

import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import servidorsimple.FileSystem;
import servidorsimple.ServirDirectorios;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Adrian Jesus
 */
public class Servidor_Interfaz extends javax.swing.JFrame {

    String path;
    ServirDirectorios sd;

    /**
     * Creates new form Servidor_Interfaz
     */
    public Servidor_Interfaz() {
        initComponents();
        try {
            Image img = ImageIO.read(getClass().getResource("/images/icon.png"));
            this.setIconImage(img);
        } catch (IOException ex) {
        }
        elegirRutaBase.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        cmd.setWrapStyleWord(false);
        cmd.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elegirRutaBase = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmd = new javax.swing.JTextArea();
        info = new javax.swing.JLabel();
        elegirbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        udpconnect = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor de Música");

        cmd.setColumns(20);
        cmd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmd.setRows(5);
        jScrollPane1.setViewportView(cmd);

        info.setText("Hasta que no se seleccione una ruta base, el servidor no se iniciará...");

        elegirbtn.setText("Elegir ruta base");
        elegirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("<html>Para permitir la conexión directa de un usuario a través de UDP active el botón:</html>");

        udpconnect.setText("Permitir Conexión Directa");
        udpconnect.setEnabled(false);
        udpconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udpconnectActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(jSeparator1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, elegirbtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(info, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 184, Short.MAX_VALUE)
                        .add(udpconnect))
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(info, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(elegirbtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(udpconnect)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 294, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que lanza un dialog para seleccionar la ruta base y lanza el
     * servidor
     *
     * @param evt informacion sobre el evento que llamo a este método
     */
    private void elegirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirbtnActionPerformed
        // TODO add your handling code here:
        int sel = elegirRutaBase.showOpenDialog(this);
        if (sel == JFileChooser.APPROVE_OPTION) {
            path = elegirRutaBase.getSelectedFile().getAbsolutePath();
            out("Se ha establecido la ruta base en: " + path);
            info.setText("Ruta base: " + path);
            if (sd == null) {
                try {
                    sd = new ServirDirectorios(path, this);
                    sd.start();
                    out("Creado en servidor...");
                } catch (Exception e) {
                }
            } else {
                sd.setPath(path);
            }
            udpconnect.setEnabled(true);

        }
    }//GEN-LAST:event_elegirbtnActionPerformed

    private void udpconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udpconnectActionPerformed
        //lanzamos o paramos el servidor udp
        if (udpconnect.isSelected()) {
            sd.initUDPBroadcast();
        } else {
            sd.stopUDPBroadcast();
        }
    }//GEN-LAST:event_udpconnectActionPerformed

    /**
     * Este método esta para simplificar la impresion por consola
     *
     * @param s string para imprimir
     */
    public void out(String s) {
        cmd.insert(s + "\n", cmd.getText().length());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor_Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cmd;
    private javax.swing.JFileChooser elegirRutaBase;
    private javax.swing.JButton elegirbtn;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton udpconnect;
    // End of variables declaration//GEN-END:variables
}
